version: "3.7"

networks:
  exelor:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "exelor_db"
    ports:
      - 5000:6000
    networks:
      - exelor
  exelor_db:
    image: ${DB_IMAGE}
    ports:
      - ${HOST_PORT}:${LOCAL_PORT}
    volumes:
      - data:${LOCAL_DATADIR}
    env_file: .env
    networks:
      - exelor

volumes:
  data:
    name: ${HOST_DATAVOLUMENAME}
    external: false # creates a volume if not present
